"""
AI analysis service using Google Gemini API.

Takes search context and generates a structured markdown report
with trade opportunity insights for a given sector.
"""

import logging
from typing import Optional

import google.generativeai as genai

from app.config import settings

logger = logging.getLogger(__name__)

# ─── Gemini Configuration ──────────────────────────────────────────────────────

_model: Optional[genai.GenerativeModel] = None


def _get_model() -> genai.GenerativeModel:
    """Lazy-initialize and return the Gemini model."""
    global _model
    if _model is None:
        if not settings.GEMINI_API_KEY:
            raise RuntimeError(
                "GEMINI_API_KEY is not configured. "
                "Set it in .env or as an environment variable. "
                "Get a free key at https://aistudio.google.com/apikey"
            )
        genai.configure(api_key=settings.GEMINI_API_KEY)
        _model = genai.GenerativeModel("gemini-2.0-flash")
        logger.info("Gemini model initialized (gemini-2.0-flash)")
    return _model


# ─── Analysis ──────────────────────────────────────────────────────────────────

ANALYSIS_PROMPT = """You are a senior trade analyst specializing in Indian markets. 
Analyze the following market data for the **{sector}** sector in India and produce 
a comprehensive, well-structured markdown report.

## Source Data
{context}

## Instructions
Generate a detailed markdown report with the following sections. Use real data from the 
sources above. Be specific with numbers, names, and facts where available. If data is 
limited, provide well-informed analysis based on your knowledge of Indian trade.

The report MUST follow this exact structure:

# Trade Opportunities Report: {sector_title} Sector — India

## Executive Summary
A concise 3-4 sentence overview of the sector's current state and key opportunities.

## Market Overview
- Current market size and growth trajectory
- Key statistics and figures
- Recent developments and trends

## Current Trade Opportunities
- Top 3-5 specific, actionable trade opportunities
- For each: description, potential, and entry strategy

## Key Players & Competitive Landscape
- Major domestic companies
- International players active in India
- Market share distribution (if available)

## Import/Export Analysis
- Current import/export volumes and values
- Top trading partner countries
- Trade balance trends

## Government Policies & Regulatory Environment
- Relevant government schemes and incentives
- Recent policy changes impacting the sector
- Regulatory requirements for market entry

## Risk Factors & Challenges
- Top 3-5 risks with brief mitigation strategies
- Market-specific challenges

## Strategic Recommendations
- 3-5 actionable recommendations for businesses looking to enter or expand
- Short-term vs long-term strategies

## Data Sources
List the sources used with their URLs.

---
*Report generated by Trade Opportunities API | Powered by AI Analysis*
"""


async def analyze_sector(sector: str, search_context: str) -> str:
    """
    Use Gemini AI to analyze the sector based on collected search data.

    Args:
        sector: The sector name (e.g., "pharmaceuticals")
        search_context: Aggregated text from web search results

    Returns:
        A structured markdown report string

    Raises:
        RuntimeError: If Gemini API key is not configured
        Exception: If Gemini API call fails
    """
    model = _get_model()

    prompt = ANALYSIS_PROMPT.format(
        sector=sector,
        sector_title=sector.title(),
        context=search_context if search_context else "No specific source data available. Use your general knowledge.",
    )

    try:
        logger.info(f"Sending analysis request to Gemini for sector: {sector}")
        response = await model.generate_content_async(prompt)

        if not response or not response.text:
            raise ValueError("Gemini returned an empty response")

        report = response.text.strip()
        logger.info(f"Received analysis for sector: {sector} ({len(report)} chars)")
        return report

    except Exception as e:
        logger.error(f"Gemini analysis failed for sector '{sector}': {e}")
        raise RuntimeError(f"AI analysis failed: {str(e)}") from e
